# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gene T Taylor
tagline:             Software etc
url:                 http://gene-t-taylor.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Gene Taylor
  url:               https://twitter.com/SplicedGene
  email:             Gene.T.Taylor@gmail.com


#pages in the navigation bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'